# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Acceptance Tests
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
      - 'master'
  pull_request: null
  # Once weekly on Wednesdays at 16:00 UTC.
  schedule:
    - cron: '0 16 * * 3'
  workflow_dispatch:

jobs:
  acceptance:
    strategy:
      matrix:
        wp: ['6.3','5.6','nightly']
        php: ['8.0','7.4']
        include:
          - wp: '6.3'
            php: '8.1'
          - wp: 'nightly'
            php: '8.1'
          - wp: '6.3'
            php: '8.2'
          - wp: 'nightly'
            php: '8.2'
      fail-fast: false
    name: WP ${{ matrix.wp }} / PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    env:
      LOCAL_PHP: ${{ matrix.php }}
      LOCAL_WP_DEBUG: 1
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        tools: composer:2.2
        coverage: none
        ini-file: development
      env:
        fail-fast: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      uses: ramsey/composer-install@v2

    - name: Install dependencies
      env:
        WP_CORE_CONSTRAINT: ${{ matrix.wp == 'nightly' && 'dev-main' || format('~{0}.0', matrix.wp) }}
      run: |
        composer require --dev --update-with-dependencies --prefer-dist "roots/wordpress-full:${WP_CORE_CONSTRAINT}"

    - name: Start Docker environment
      run: composer test:start

    - name: Run the tests
      run: composer test:acceptance

    - name: Upload test artifacts
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: acceptance-wp-${{ matrix.wp }}-php-${{ matrix.php }}
        path: tests/_output
