# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Deploy Tag
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: The version number of the release

concurrency: WordPress.org

permissions: {}

jobs:
  deploy:
    name: Deploy Tag
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-deploy-tag.yml@8d8ccc89b04d85ae8d064774d63d8725799f4224 # 2.7.3
    permissions:
      contents: write
      issues: write
      pull-requests: write
      attestations: write
      id-token: write
    with:
      deploy: true
      plugin: wp-crontrol
      readme: readme.txt
      version: ${{ github.event_name != 'workflow_dispatch' && github.event.release.tag_name || github.event.inputs.version }}
      username: johnbillion
      did: did:plc:kjnlj6j6hvasaxc6rchd3pnu
      fair-path: .did/fair.json
    secrets:
      WPORG_SVN_PASSWORD: ${{ secrets.WPORG_SVN_PASSWORD }}
      FAIR_VERIFICATION_KEY: ${{ secrets.FAIR_VERIFICATION_KEY }}
