# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Integration Tests
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
    paths:
      - '.github/workflows/integration-tests.yml'
      - 'tests/**'
      - '**.css'
      - '**.js'
      - 'src/**'
      - 'wp-crontrol.php'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'docker-compose.yml'
      - 'package.json'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/integration-tests.yml'
      - 'tests/**'
      - '**.css'
      - '**.js'
      - 'src/**'
      - 'wp-crontrol.php'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'docker-compose.yml'
      - 'package.json'
  workflow_dispatch:

permissions: {}

jobs:
  test:
    name: WP ${{ matrix.wp }}
    permissions:
      contents: read
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-integration-tests.yml@c822b61d10775daab8f890bd4c69e966ee5daa47
    strategy:
      # See the following for PHP compatibility of WordPress versions:
      # https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/
      matrix:
        wp:
          # Three most recent versions of WordPress
          - '6.9-RC1'
          - '6.8'
          - '6.7'
        php:
          # Most recent version of PHP supported by all of the above, plus 7.4
          - '8.3'
          - '7.4'
        include:
          # Latest WordPress on PHP 8.4
          - wp: '6.9-RC1'
            php: '8.4'
          # Oldest supported WordPress on its newest and oldest supported PHP:
          - wp: '6.4'
            php: '8.3'
          - wp: '6.4'
            php: '7.4'
      fail-fast: false
    with:
      php: ${{ matrix.php }}
      wp: ${{ matrix.wp }}
