# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Verify Plugin Distribution
on:
  schedule:
    # Once per hour
    #
    #        ┌───────────── minute           (0 - 59)
    #        │  ┌────────── hour             (0 - 23)
    #        │  │  ┌─────── day of the month (1 - 31)
    #        │  │  │  ┌──── month            (1 - 12 or JAN-DEC)
    #        │  │  │  │  ┌─ day of the week  (0 - 6 or SUN-SAT)
    #        │  │  │  │  │
    #        │  │  │  │  │
    #        │  │  │  │  │
    - cron: '20 *  *  *  *'
  push:
    branches:
      - 'develop'
    paths:
      - '.github/workflows/verify-distribution.yml'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/verify-distribution.yml'
  workflow_dispatch:

permissions: {}

jobs:
  verify:
    name: Verify Plugin Distribution
    permissions: {}
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-verify-distribution.yml@5a327134e8fabebf5fbf0e8e31c46fa4d36b0d23 # v2.1.0-beta.2
    with:
      plugin: wp-crontrol
      owner: johnbillion
